
import com.departamento.Departamento;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */

public class TelaCriarDep extends javax.swing.JFrame {

    private Controlador controladorSistema;
    
    public TelaCriarDep() {
        initComponents();
        this.setTitle("Criar Departamento");
        this.controladorSistema = new Controlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNomeDepart = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCodigoDep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoQtdFunciDep = new javax.swing.JTextField();
        btnVoltarPaginaInicial = new javax.swing.JButton();
        btnCriarDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel9.setBackground(new java.awt.Color(243, 244, 246));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(36, 89, 162));
        jPanel12.setRequestFocusEnabled(false);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoUnespMenor.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 58)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sistema Universitário");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(15, 15, 15))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(53, 53, 53))
        );

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 140));

        jPanel13.setBackground(new java.awt.Color(242, 236, 78));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 1030, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 58, 138));
        jLabel15.setText("<html><center> <h1>Criar departamento</h1><p>Preencha os campos abaixo para criar um departamento</p> </center></html>");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 760, 110));

        jPanel14.setLayout(new java.awt.CardLayout());
        jPanel9.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 58, 138));
        jLabel1.setText("<html><p>Nome do departamento:</p></html>");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));
        jPanel9.add(campoNomeDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 790, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 58, 138));
        jLabel4.setText("<html><p>Código do departamento:</p></html>");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        campoCodigoDep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoDepFocusLost(evt);
            }
        });
        jPanel9.add(campoCodigoDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 790, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 58, 138));
        jLabel5.setText("Quantidade de funcionários:");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        campoQtdFunciDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQtdFunciDepActionPerformed(evt);
            }
        });
        jPanel9.add(campoQtdFunciDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 790, -1));

        btnVoltarPaginaInicial.setBackground(new java.awt.Color(30, 58, 138));
        btnVoltarPaginaInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltarPaginaInicial.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarPaginaInicial.setText("Voltar para a página inicial");
        btnVoltarPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPaginaInicialActionPerformed(evt);
            }
        });
        jPanel9.add(btnVoltarPaginaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, -1, -1));

        btnCriarDep.setBackground(new java.awt.Color(30, 58, 138));
        btnCriarDep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriarDep.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarDep.setText("Criar departamento");
        btnCriarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarDepActionPerformed(evt);
            }
        });
        jPanel9.add(btnCriarDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoQtdFunciDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQtdFunciDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQtdFunciDepActionPerformed

    private void btnVoltarPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPaginaInicialActionPerformed
        
        
    }//GEN-LAST:event_btnVoltarPaginaInicialActionPerformed

    private void btnCriarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarDepActionPerformed
        
        String nomeDepartamento = this.campoNomeDepart.getText();
        String codigoDepartamento = this.campoCodigoDep.getText();
        int numFuncionarios = Integer.parseInt(this.campoQtdFunciDep.getText());


        if(this.controladorSistema.criarDepartamento(codigoDepartamento, nomeDepartamento, numFuncionarios))
        {
            JOptionPane.showMessageDialog(this, "Departamento criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }else{

            JOptionPane.showMessageDialog(this, "Não foi possível criar o departamento!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        this.campoCodigoDep.setText("");
        this.campoNomeDepart.setText("");
        this.campoQtdFunciDep.setText("");
        
    }//GEN-LAST:event_btnCriarDepActionPerformed

    private void campoCodigoDepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoDepFocusLost
        
        String codigoDepartamento = campoCodigoDep.getText();
        
        if(this.controladorSistema.existeDepartamento(codigoDepartamento))
        {
            Departamento dep = this.controladorSistema.getDepartamentoPorCodigo(codigoDepartamento);
            
            if(dep != null)
            {
                campoNomeDepart.setText(dep.getNome());
                String qtdFuncionarios = Integer.toString(dep.getQtdFuncionarios());
                campoQtdFunciDep.setText(qtdFuncionarios);
                btnCriarDep.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Esse departamento já existe!", "Aviso", JOptionPane.WARNING_MESSAGE);
                this.campoCodigoDep.setText("");
                this.campoNomeDepart.setText("");
                this.campoQtdFunciDep.setText("");
            }
        }
        else
        {
            campoNomeDepart.setText("");
            campoQtdFunciDep.setText("");
            btnCriarDep.setEnabled(true);
        }
        
    }//GEN-LAST:event_campoCodigoDepFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarDep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarDep;
    private javax.swing.JButton btnVoltarPaginaInicial;
    private javax.swing.JTextField campoCodigoDep;
    private javax.swing.JTextField campoNomeDepart;
    private javax.swing.JTextField campoQtdFunciDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
