/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class TelaCriarTecnico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCriarTecnico
     */
    public TelaCriarTecnico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVoltarPaginaInicial = new javax.swing.JButton();
        btnCriarTecnico = new javax.swing.JButton();
        campoNomeTecnico = new javax.swing.JTextField();
        campoCodigoTecnico = new javax.swing.JTextField();
        campoSalarioTecnico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNivelTecnico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoFunTecnico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoCodigoDepTecnico = new javax.swing.JTextField();

        jPanel9.setBackground(new java.awt.Color(243, 244, 246));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(36, 89, 162));
        jPanel12.setRequestFocusEnabled(false);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoUnespMenor.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sistema Universitário");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(15, 15, 15))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(53, 53, 53))
        );

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 140));

        jPanel13.setBackground(new java.awt.Color(242, 236, 78));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 960, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 58, 138));
        jLabel15.setText("<html><center> <h1>Criar funcionário técnico</h1><p>Preencha os campos abaixo para criar um funcionário técnico</p> </center></html>");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 760, 110));

        jPanel14.setLayout(new java.awt.CardLayout());
        jPanel9.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 58, 138));
        jLabel1.setText("<html><p>Nome do funcionário:</p></html>");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 58, 138));
        jLabel4.setText("<html><p>Código do funcionário:</p></html>");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 58, 138));
        jLabel5.setText("Salário do funcionário:");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        btnVoltarPaginaInicial.setBackground(new java.awt.Color(30, 58, 138));
        btnVoltarPaginaInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltarPaginaInicial.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarPaginaInicial.setText("Voltar para a página inicial");
        btnVoltarPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPaginaInicialActionPerformed(evt);
            }
        });
        jPanel9.add(btnVoltarPaginaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, -1, -1));

        btnCriarTecnico.setBackground(new java.awt.Color(30, 58, 138));
        btnCriarTecnico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriarTecnico.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarTecnico.setText("Criar técnico");
        btnCriarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarTecnicoActionPerformed(evt);
            }
        });
        jPanel9.add(btnCriarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, -1, -1));
        jPanel9.add(campoNomeTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 760, -1));
        jPanel9.add(campoCodigoTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 760, -1));

        campoSalarioTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalarioTecnicoActionPerformed(evt);
            }
        });
        jPanel9.add(campoSalarioTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 760, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 58, 138));
        jLabel2.setText("Nível do técnico:");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        campoNivelTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNivelTecnicoActionPerformed(evt);
            }
        });
        jPanel9.add(campoNivelTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 760, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 58, 138));
        jLabel3.setText("Função do técnico:");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        campoFunTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFunTecnicoActionPerformed(evt);
            }
        });
        jPanel9.add(campoFunTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 760, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 58, 138));
        jLabel7.setText("Código do departamento:");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        campoCodigoDepTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoDepTecnicoActionPerformed(evt);
            }
        });
        jPanel9.add(campoCodigoDepTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 760, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSalarioTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalarioTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSalarioTecnicoActionPerformed

    private void campoNivelTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNivelTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNivelTecnicoActionPerformed

    private void btnVoltarPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPaginaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarPaginaInicialActionPerformed

    private void btnCriarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarTecnicoActionPerformed

    private void campoFunTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFunTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFunTecnicoActionPerformed

    private void campoCodigoDepTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoDepTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoDepTecnicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarTecnico;
    private javax.swing.JButton btnVoltarPaginaInicial;
    private javax.swing.JTextField campoCodigoDepTecnico;
    private javax.swing.JTextField campoCodigoTecnico;
    private javax.swing.JTextField campoFunTecnico;
    private javax.swing.JTextField campoNivelTecnico;
    private javax.swing.JTextField campoNomeTecnico;
    private javax.swing.JTextField campoSalarioTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
