
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class TelaCriarEfe extends javax.swing.JFrame {

    /**
     * Creates new form TelaCriarEfe
     */
    private Controlador controladorSistema;

    public TelaCriarEfe(Controlador controladorSistema) {
        this.setTitle("Criar Efetivo");
        this.controladorSistema = controladorSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVoltarPaginaInicial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoAreaDocenteEfetivo = new javax.swing.JTextField();
        campoCodigoDepDocenteEfetivo = new javax.swing.JTextField();
        campoTitulacaoDocenteEfetivo = new javax.swing.JTextField();
        campoCodigoDocenteEfetivo = new javax.swing.JTextField();
        campoNomeDocenteEfetivo = new javax.swing.JTextField();
        btnCriarEfetivo = new javax.swing.JButton();
        campoNivelDocenteEfetivo = new javax.swing.JComboBox<>();
        campoSalarioDocenteEfetivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel9.setBackground(new java.awt.Color(243, 244, 246));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(36, 89, 162));
        jPanel12.setRequestFocusEnabled(false);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoUnespMenor.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sistema Universitário");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(15, 15, 15))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(53, 53, 53))
        );

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 970, 140));

        jPanel13.setBackground(new java.awt.Color(242, 236, 78));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 960, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 58, 138));
        jLabel15.setText("<html><center> <h1>Criar docente efetivo</h1><p>Preencha os campos abaixo para criar um docente técnico</p> </center></html>");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 760, 110));

        jPanel14.setLayout(new java.awt.CardLayout());
        jPanel9.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 58, 138));
        jLabel1.setText("<html><p>Nome do docente:</p></html>");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 58, 138));
        jLabel4.setText("<html><p>Código do docente:</p></html>");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 58, 138));
        jLabel5.setText("Salário do docente:");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        btnVoltarPaginaInicial.setBackground(new java.awt.Color(30, 58, 138));
        btnVoltarPaginaInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltarPaginaInicial.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarPaginaInicial.setText("Voltar para a página inicial");
        btnVoltarPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPaginaInicialActionPerformed(evt);
            }
        });
        jPanel9.add(btnVoltarPaginaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 58, 138));
        jLabel2.setText("Nível do docente:");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 58, 138));
        jLabel3.setText("Titulação do docente:");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 58, 138));
        jLabel7.setText("Código do departamento:");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 58, 138));
        jLabel6.setText("Área do docente:");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));
        jPanel9.add(campoAreaDocenteEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 780, -1));

        campoCodigoDepDocenteEfetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoDepDocenteEfetivoActionPerformed(evt);
            }
        });
        jPanel9.add(campoCodigoDepDocenteEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 780, -1));

        campoTitulacaoDocenteEfetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTitulacaoDocenteEfetivoActionPerformed(evt);
            }
        });
        jPanel9.add(campoTitulacaoDocenteEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 780, -1));
        jPanel9.add(campoCodigoDocenteEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 780, -1));
        jPanel9.add(campoNomeDocenteEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 780, -1));

        btnCriarEfetivo.setBackground(new java.awt.Color(30, 58, 138));
        btnCriarEfetivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriarEfetivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarEfetivo.setText("Criar efetivo");
        btnCriarEfetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEfetivoActionPerformed(evt);
            }
        });
        jPanel9.add(btnCriarEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 660, -1, -1));

        campoNivelDocenteEfetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D1", "D2", "D3" }));
        campoNivelDocenteEfetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNivelDocenteEfetivoActionPerformed(evt);
            }
        });
        jPanel9.add(campoNivelDocenteEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        campoSalarioDocenteEfetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalarioDocenteEfetivoActionPerformed(evt);
            }
        });
        jPanel9.add(campoSalarioDocenteEfetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 780, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPaginaInicialActionPerformed
        this.dispose();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(controladorSistema).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnVoltarPaginaInicialActionPerformed

    private void campoTitulacaoDocenteEfetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTitulacaoDocenteEfetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTitulacaoDocenteEfetivoActionPerformed

    private void btnCriarEfetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEfetivoActionPerformed
        String nomeEfetivo = this.campoNomeDocenteEfetivo.getText();
        String codigoEfetivo = this.campoCodigoDepDocenteEfetivo.getText();

        try
        {
            double salarioEfetivo = Double.parseDouble(this.campoSalarioDocenteEfetivo.getText());
        
            String nivelDocente = this.campoNivelDocenteEfetivo.getSelectedItem().toString();
            String titulacaoDocente = this.campoTitulacaoDocenteEfetivo.getText();
            String areaDocente = this.campoAreaDocenteEfetivo.getText();

            if(this.controladorSistema.criarEfetivo(codigoEfetivo, nomeEfetivo, salarioEfetivo, nivelDocente, titulacaoDocente, areaDocente, codigoEfetivo))
            {
                JOptionPane.showMessageDialog(this, "Funcionário Efetivo criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }else{

                JOptionPane.showMessageDialog(this, "Não foi possível criar o Funcionário Efetivo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Salário deve ser um número!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        this.campoAreaDocenteEfetivo.setText("");
        this.campoCodigoDepDocenteEfetivo.setText("");
        this.campoCodigoDocenteEfetivo.setText("");
        this.campoTitulacaoDocenteEfetivo.setText("");
        this.campoNomeDocenteEfetivo.setText("");
        this.campoSalarioDocenteEfetivo.setText("");
    }//GEN-LAST:event_btnCriarEfetivoActionPerformed

    private void campoNivelDocenteEfetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNivelDocenteEfetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNivelDocenteEfetivoActionPerformed

    private void campoCodigoDepDocenteEfetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoDepDocenteEfetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoDepDocenteEfetivoActionPerformed

    private void campoSalarioDocenteEfetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalarioDocenteEfetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSalarioDocenteEfetivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarEfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarEfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarEfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarEfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Controlador controladorSistema) {
                new TelaCriarEfe(controladorSistema).setVisible(true);
            }
            
            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarEfetivo;
    private javax.swing.JButton btnVoltarPaginaInicial;
    private javax.swing.JTextField campoAreaDocenteEfetivo;
    private javax.swing.JTextField campoCodigoDepDocenteEfetivo;
    private javax.swing.JTextField campoCodigoDocenteEfetivo;
    private javax.swing.JComboBox<String> campoNivelDocenteEfetivo;
    private javax.swing.JTextField campoNomeDocenteEfetivo;
    private javax.swing.JTextField campoSalarioDocenteEfetivo;
    private javax.swing.JTextField campoTitulacaoDocenteEfetivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
